---
- name: Add the user 'node_exporter' as a system user, with no login, no home
  ansible.builtin.user:
    name: node_exporter
    comment: monitoring user
    shell: /usr/sbin/nologin
    create_home: false
    system: true

- name: download files to a target path
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz
    dest: /tmp

- name: Extract the downloaded archive
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-1.9.0.linux-amd64.tar.gz
    dest: /tmp 
    remote_src: yes

- name: Copy binary from extracted folder to /usr/local/bin/node_exporter
  ansible.builtin.copy:
    src: /tmp/node-exporter-1.9.0.linux-amd64/
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes

- name: Copy the created systemd file to /etc/systemd/system
  ansible.builtin.copy:
    src: files/node_exporter.service
    dest: /etc/systemd/system/
    notify: systemd-handler

- name: Start and enable the systemd service
  ansible.builtin.service:
    name: node_exporter.service
    state: enabled
    started: yes

- name: Open port 9100 in the firewall
  ansible.posix.firewalled:
    port: 9100/tcp
    permanent: true
    state: enabled

